### PR TITLE
Bump to latest k8s version

### PR DESCRIPTION
**Pull request by birgirst**
Need the updated api endpoint for deployments.

### CODE REVIEW

**Comment by oyvindio** [comment]
> LGTM

Actually, it looks like there is some issue in the CI build here

**Comment by birgirst** [comment]
Thanks I see it. I'll dig and fix.

**Comment by mortenlj** [comment]
> Thanks I see it. I'll dig and fix.

It's the changes introduced here that is hitting you: https://github.com/fiaas/k8s/commit/854868e22f3ae601b3405c89cb05bbc76eae494d
I think the problem is that the mock is not returning a value that can be parsed as a datetime, but that's just a quick guess. Something related to the interaction between the mock and datetime handling at least.

**Comment by mortenlj** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- tests/fiaas_skipper/deploy/test_bootstrap.py  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/fiaas/skipper/pullRequest?prid=5624435&bid=18424566)

**Pull request merged**
